-- Create client_type data type

DROP TYPE IF EXISTS public.account_type;

CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);


-- Table structure for table "classification"

DROP TABLE IF EXISTS public.classification CASCADE;

CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);


-- Table structure for table "account"

DROP TABLE IF EXISTS public.account CASCADE;

CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR(20) NOT NULL,
    account_lastname VARCHAR(30) NOT NULL,
    account_email VARCHAR(60) NOT NULL,
    account_password VARCHAR(20) NOT NULL,
    account_type account_type DEFAULT 'Client',
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);


-- Table structure for table "inventory"

DROP TABLE IF EXISTS public.inventory CASCADE;

CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_id INT NOT NULL,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_description TEXT,
    inv_image VARCHAR(255),
    inv_thumbnail VARCHAR(255),
    inv_price DECIMAL(10, 2),
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
);


-- Insert initial classifications
INSERT INTO classification (classification_name) 
VALUES 
  ('Custom'),
  ('Sedan'),
  ('Sport'),
  ('SUV'),
  ('Truck');