-- *********************************************
-- Create client_type data type
-- *********************************************

DROP TYPE IF EXISTS public.account_type;

CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);


-- Table structure for table "classification"


DROP TABLE IF EXISTS public.classification CASCADE;

CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);


-- Query 4
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Query 6
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');